### ISSUE TITLE
Add Evil Bob and Drunken Dwarf random event sounds

### ISSUE THREAD

**Issue by winterdaze** [Broooklyn/runelite-external-plugins#1]
I think the soundeffect IDs are 333 and 2297, double check them tho

**Comment by Broooklyn** [comment]
The IDs are correct, will just have to get confirmation whether they are source npc or source null. If null, evil bob should already be covered by the pet sounds config(although I'd make a separate config for random events). Will wait for the randoms to confirm.

**Comment by Broooklyn** [comment]
Added in 74bb2779e51660c3701e9073b3c70fe6240df720
