### ISSUE TITLE
Mute Magic Trees

### ISSUE THREAD

**Issue by FlamingoChest** [Broooklyn/runelite-external-plugins#103]
This shouldve been the first thing honestly.

**Comment by beanamonster** [comment]
Please for the love of all things holy

**Comment by UncookedPants27** [comment]
10000% agree, my ears wont stop ringing! Mute the magic trees!

**Comment by magnus1500** [comment]
I'm trying to use annoyance mute to mute magic trees using the sound IDs (3134, 3135, 3136) and they are present in the Muted Sounds field - but the tree still comes through. I don't want to turn off environmental sounds completely just these damn trees. I leave my sound on for some stuff and every herb run I get BLASTED with magic tree sound. Its dreadful

**Comment by JZomDev** [comment]
Done in https://github.com/Broooklyn/runelite-external-plugins/commit/bda54623af1a75e0fbf8b1e9577708e1ce7f7524
