### ISSUE TITLE
Smoke Devils

### ISSUE THREAD

**Issue by SmokeDevils** [Broooklyn/runelite-external-plugins#111]
Please make a sound that mutes the smoke devil sound affect when it is attacking. When I am doing a burst task at the smoke devils, I like to listen to my Ice barrage sound so I know I'm still attacking them but I would rather not hear the smoke devil sounds.

**Comment by samuelcolburn** [comment]
You can use the Annoyance Mute plugin to mute any set of game sounds as long as you know the ID. You can also use the Visual sounds plugin to find the ID(s) of all the smoke devil attack sounds as you're fighting them, so you can mute them with annoyance mute.
