### ISSUE TITLE
Annoyance Mute - LocalPlayer NullPointerException

### ISSUE THREAD

**Issue by InfernoStats** [Broooklyn/runelite-external-plugins#116]
[This line](https://github.com/Broooklyn/runelite-external-plugins/blob/annoyance-mute/src/main/java/com/brooklyn/annoyancemute/AnnoyanceMutePlugin.java#L511) will raise a `NullPointerException` when `localPlayer` is null.

`localTeleport` is called on [this line](https://github.com/Broooklyn/runelite-external-plugins/blob/annoyance-mute/src/main/java/com/brooklyn/annoyancemute/AnnoyanceMutePlugin.java#L436) in `setUpMutes` which is ran during the `startUp` function. On client load, when the plugin is loaded, the local player will be null.

**Comment by JZomDev** [comment]
This should be fixed in https://github.com/Broooklyn/runelite-external-plugins/pull/117 when I get brooklyn to review my work. 

I broke the teleport stuff when I changed to the SoundEffect system to fix the Smashing! issue. Whoops!
