### ISSUE TITLE
Duke sucellus fermentation vat not muting

### ISSUE THREAD

**Issue by RyanRooney-git** [Broooklyn/runelite-external-plugins#119]
the sound was muted prior to today 9/18/2023 for about 4 days but was unmuted today. i've tried using the ID 47536, 47537 and the name "Fermentation Vat" as well as uninstalling and resetting the plugin to no avail.

**Comment by JZomDev** [comment]
Sound IDs are not 47536 nor 47537. Sound ID was provided on discord.
