### ISSUE TITLE
prayers no longer muting

### ISSUE THREAD

**Issue by JFacini** [Broooklyn/runelite-external-plugins#120]
I usually play with prayer deactiviation sounds muted. Over the last 2 days or so the plugin has stopped muting these sounds. 

![image](https://github.com/Broooklyn/runelite-external-plugins/assets/116046039/0df68707-10e2-4501-8cfa-a94c2ae4b3a9)

I also tested muting prayer activiations, and those were not muting either. Additionally, graardor's steps are no longer being muted by this plugin and I had to turn area sounds off.

I love this plugin so much -- thanks for making it!

**Comment by JZomDev** [comment]
This is fixed in #117 , turn off and turn back on plugin in mean time. Sorry!
