### ISSUE TITLE
Magic Tree Mute Resetting

### ISSUE THREAD

**Issue by Scandalari** [Broooklyn/runelite-external-plugins#133]
Noticed this issue started earlier on the 7th of November (When servers went down to fix a mobile crashing issue)

Magic Trees seem to be "unmuted" when a tree "regrows" within a "earshot" the player. The setting is still checked for them to be muted, and can easily be re-muted by either turning plugin off and back on, or going into the settings and unmuting, then re-muting.  It seems to be unmuting the specific tree (if that makes sense?) When it happens I can run from the northern Magics in WC Guild to the southern ones, and the sound stops even though I'm right next to a Magic Tree.

I'm not a coder, nor am I able to give any insight on why this might be happening. I'm just a dude that likes to hear the choppy chop without the constant chimes from Magic trees.

(Just tested this on a busier world: Looks like the mute is getting turned off for any trees that regrow in a loaded chunk. Not just ones in earshot. Had a tree regrow while I was banking in WC Guild and it was unmuted. I don't know how any of this works, but trees are muted until they regrow.)

I can record a video through OBS if that would be helpful at all.

**Comment by JZomDev** [comment]
Jagex this week introduced the idea of ambient sounds being created on an in game event rather than being generated at map loading, causing the sounds to be re-added to the list of ambient sounds that play on the client.

I will have to take a look at see what's going on later today.

**Comment by JZomDev** [comment]
This will be fixed next update of annoyance mute https://github.com/Broooklyn/runelite-external-plugins/commit/3a47d72a2257b87d86b50f72ca1df0197e9f8a39
