### ISSUE TITLE
Add Onyx (e) bolts id 2917

### ISSUE THREAD

**Issue by ThaFrenchFry** [Broooklyn/runelite-external-plugins#135]
Life_leech is a really long really obnoxious sound, please add it as a toggle for others to find easily

**Comment by JZomDev** [comment]
![image](https://github.com/Broooklyn/runelite-external-plugins/assets/14265490/8b095680-5e9d-4b2f-90a3-fea6b0421a7c)

People can already use this plugin to find sounds they want to mute themselves, rather than manually adding every sound & a checkbox.
