### ISSUE TITLE
Feature Request: Muting Glassblowing

### ISSUE THREAD

**Issue by SuperCoolDude** [Broooklyn/runelite-external-plugins#140]
Glassblowing is a slow progression, often needing like 10k or so per level beyond 75 crafting, so it would be great to mute this loud sound.

**Comment by JZomDev** [comment]
Instead of adding a bunch of single item things to mute, use 
![image](https://github.com/Broooklyn/runelite-external-plugins/assets/14265490/5560e9d1-0ac4-4cb2-afae-c51e85327989)

And add the sound id yourself to the custom mute list at the bottom (not the ambient mute section)

**Comment by SuperCoolDude** [comment]
Thank you! If anyone needs this, glassblowing ID is 2724 to mute.
