### ISSUE TITLE
[Request] Mute cow "moo"

### ISSUE THREAD

**Issue by tapilogali** [Broooklyn/runelite-external-plugins#15]
Possible to add an option to mute cow "Moo" near crafting guild?

**Comment by Broooklyn** [comment]
Added in v1.4

**Comment by tapilogali** [comment]
Yeah, I missed it, sorry about that.

**Comment by Broooklyn** [comment]
Oh no you didn't miss anything, I just added it last night per your request and was letting you know I had done so

**Comment by tapilogali** [comment]
Oh wow, thank you, I appreciate it!

**Comment by Broooklyn** [comment]
You're welcome. If you have any other requests feel free to open another issue :)
