### ISSUE TITLE
Mute others area sounds not working

### ISSUE THREAD

**Issue by sstephenss** [Broooklyn/runelite-external-plugins#153]
I can still hear everyones woodcutting at wintertodt

**Comment by JZomDev** [comment]
If you mute woodcutting it mutes everyone's sounds of woodcutting. There is no option to mute only other's woodcutting sounds.

**Comment by JZomDev** [comment]
upon inspection of this, I cannot recreate this issue. "Others' Area Sounds" works correctly.
