### ISSUE TITLE
Nail Beasts from Temple Trekking

### ISSUE THREAD

**Issue by summercatmeow** [Broooklyn/runelite-external-plugins#21]
I think these things annoying screeches would make a very good addition to this plugin.

**Comment by tapilogali** [comment]
Also lesser demons possible?

**Comment by Broooklyn** [comment]
I actually recently started chipping away at the lesser demon champion scroll so I definitely feel you on those. Grabbed the nail beast SoundIDs so I'll get these added soon. Thanks for the suggestions.

**Comment by Broooklyn** [comment]
Added both in v1.5
