### ISSUE TITLE
Magic Trees

### ISSUE THREAD

**Issue by Abyssal-Flames** [Broooklyn/runelite-external-plugins#3]
Could you add an option to mute the humming/whirring that magic trees produce? I love hearing my character chopping, but can't stand the sound those trees make.

**Comment by Broooklyn** [comment]
It's a bit tricker than the other sounds I currently have muted in the plugin, but know it is being looked into. Thanks for the suggestion.

**Comment by Abyssal-Flames** [comment]
I appreciate your willingness to look into it though! It'd be so cool if you managed to make it happen.

**Comment by 0xDREAMS** [comment]
Hi, just voicing that this is literally the only sound I'm interested in muting. Would greatly appreciate you finding a way to get rid of it. <3

**Comment by Wynadorn** [comment]
Runelite's mute ambient sound will mute magic trees, it's implemented in this commit:
https://github.com/runelite/runelite/commit/099221993ab8802993acf4ffccb4ba19a9b5a2c9
Specifically ```client.getAmbientSoundEffects().clear();``` maybe you can discover the IDs in ```getAmbientSoundEffects() ```

Also see: https://github.com/runelite/runelite/issues/12526

Hope this helps implementing the mute magic tree sound loop

**Comment by Odinnh** [comment]
> Runelite's mute ambient sound will mute magic trees, it's implemented in this commit: [runelite/runelite@0992219](https://github.com/runelite/runelite/commit/099221993ab8802993acf4ffccb4ba19a9b5a2c9) Specifically `client.getAmbientSoundEffects().clear();` maybe you can discover the IDs in `getAmbientSoundEffects() `
> 
> Also see: [runelite/runelite#12526](https://github.com/runelite/runelite/issues/12526)
> 
> Hope this helps implementing the mute magic tree sound loop

https://oldschool.runescape.wiki/w/List_of_in-game_sound_IDs the IDs according to this list are 3134, 3135, 3136 (possibly 3137 not sure) 

tried muting those specific ones but did not do anything, most sounds i checked will be muted by this plugin

**Comment by JZomDev** [comment]
Closed in https://github.com/Broooklyn/runelite-external-plugins/commit/bda54623af1a75e0fbf8b1e9577708e1ce7f7524
