### ISSUE TITLE
Smart Metronome: Possible add slayer locations? 

### ISSUE THREAD

**Issue by naml-s** [Broooklyn/runelite-external-plugins#4]
Hi mate sorry if this not right way to do this..

Cheers for plugin it works well and I like it.. 

At first I thought it would be nice to add slayer locations to plugin e.g. Catacombs, Slayer Tower, Stronghold Dungeon etc 

After this I thought it would be better to be able to toggle locations as well however I imagine, although have no idea, this will be trickier. 

Cheers
Nam

**Comment by Broooklyn** [comment]
Thanks for the suggestion! I agree it would be nice to choose which regions to mute.

**Comment by Broooklyn** [comment]
Thanks again for the suggestion, I have added location/activity toggles in v1.2 (d39fce62c14326ef4b7674be40a74248d8f2a827). You should see the update soon, pending its approval.

![image](https://user-images.githubusercontent.com/54762282/92668988-4c995480-f2de-11ea-9a50-1bef0f33297c.png)
