### ISSUE TITLE
Suggestion: Mute the tone from Magic Trees

### ISSUE THREAD

**Issue by Canno1i** [Broooklyn/runelite-external-plugins#40]
Inside the addon, there are multiple skilling mutes. One of which is woodcutting. While this does mute the chopping of the axe tone, which is a minor annoyance; I have been spending a decent amount of time afking at magic grove in wc guild. The jingle that is being made is driving me nuts. I suggest that, if possible, a mute to magic trees annoying tone be added to the plugin!

**Comment by Broooklyn** [comment]
Duplicate of #3
