### ISSUE TITLE
Plank make mute

### ISSUE THREAD

**Issue by TaylorAbraham** [Broooklyn/runelite-external-plugins#5]
Could we please get a mute for plank make? I hate turning off my sound every time for it, it's the worst sound in the game.

**Comment by Broooklyn** [comment]
Thanks for the suggestion, I'll get that one added

**Comment by Broooklyn** [comment]
Added in 7c922a8fd8f7dbf3af2fb0f7ff71f9d59004f2af 

Thanks for the suggestion!
