### ISSUE TITLE
Mute the birds and the bees (area sounds in Farming Guild)

### ISSUE THREAD

**Issue by OzzyCallooh** [Broooklyn/runelite-external-plugins#55]
If you've spent even 10 seconds in the Farming Guild you'll know what I'm talking about: it's one of the densest locations for area sounds. Constant owl hooting, bird chirping and fly/bee buzzing sounds. Almost sounds like a busy city road and the random nature of the sounds just amplifies the annoyance. I would love it if this plugin could mute these sounds.

**Comment by Broooklyn** [comment]
See #3
