### ISSUE TITLE
Suggestion remove  "select" sound

### ISSUE THREAD

**Issue by thashaman** [Broooklyn/runelite-external-plugins#67]
any chance you could add a remove the "select" sound, for instance when you click the activate quick-prayers button. that clicking sound throws me off trying to prayflick. I'd like to play with sounds and i tend to pray flick a lot.

big thanks!

**Comment by kelltom** [comment]
THIS. Please, it would be so nice.

**Comment by thashaman** [comment]
Hey guys, any chance on feedback regarding this? I might of overlooked a setting maybe idk.

Thanks!

**Comment by Broooklyn** [comment]
At the bottom of the annoyance mute settings you can add `2266` for the select sound and `2663` for the de-select sound, if you want that too.

**Comment by kelltom** [comment]
Thank you! I’ll try it tomorrow

**Comment by thashaman** [comment]
Works like a charm! Thabks a lot!
